### ISSUE TITLE
Create a QR code Scanner 

### ISSUE THREAD

**Issue by fabricekalvanda** [MobileApps-Cascadia/pollinator-pathway-android#11]
DoD: Done when we have the QR code page created to hold the QR code feature

**Comment by Bansenauer-Cascadia** [comment]
@fabricekalvanda - please update the DoD in relation to the updated feature - https://github.com/MobileApps-Cascadia/pollinator-pathway-android/projects/3#card-73028961

**Comment by shahinnezam** [comment]
Moving to backlog
