### ISSUE TITLE
Create Wiki

### ISSUE THREAD

**Issue by AndrealHarrison** [MobileApps-Cascadia/pollinator-pathway-android#5]
Create wiki page on GitHub with general information about project scope and stakeholders.

DOD: Wiki page has been created and updated to reflect current state of project as know at the time.

**Comment by Bansenauer-Cascadia** [comment]
Please assign only one person to an issue. That is the person who is responsible for tracking it through the DoD. 
It's best if the assignee is the one to open the Slack thread on the issue (by copying  and pasting the issue's URL into a Slack message on the Spring channel, e.g., https://github.com/MobileApps-Cascadia/pollinator-pathway-android/issues/5)

**Comment by shahinnezam** [comment]
DOD: Wiki page created and updated with pollinator information and stakeholders
