### ISSUE TITLE
create data model

### ISSUE THREAD

**Issue by AndrealHarrison** [MobileApps-Cascadia/pollinator-pathway-android#52]
Create a conceptual data model. done when data points are defined for tables

**Comment by Akohler28** [comment]
![PollinatorDataModel](https://user-images.githubusercontent.com/43833115/149046442-f96b2fbd-26eb-4d70-8813-fb683bfdb6ce.png)

**Comment by Akohler28** [comment]
![PollinatorDataModel](https://user-images.githubusercontent.com/43833115/149574567-8fd187c8-06ba-401c-baa9-60c785ff4c8e.png)

Updated "Site" to "Planting" per client request
