### ISSUE TITLE
Updating data model with new client suggestions

### ISSUE THREAD

**Issue by shahinnezam** [MobileApps-Cascadia/pollinator-pathway-android#73]
DOD: 
QR code on planting and boxes (Planting public facing, boxes for registration)
Add phone number to profile
Move picture from profile to planting
change all "site" language to "planting"
Add email to profile
Add organization type to profile
Possibly add location type (Church, farm, school, etc) to planting

**Comment by Akohler28** [comment]
![PollinatorDataModel](https://user-images.githubusercontent.com/43833115/150590129-2cd261e1-cc44-4ae2-b14a-7c6eae6ef675.png)
